export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';

export const SUCCESS_NOTIFICATION = 'SUCCESS_NOTIFICATION';
export const ERROR_NOTIFICATION = 'ERROR_NOTIFICATION';

export const SET_USER = 'SET_USER';
export const SET_OTHER_USERS = 'SET_OTHER_USERS';
export const SET_ACTIVE_USERS = 'SET_ACTIVE_USERS';

export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_CHAT_WITH = 'SET_CHAT_WITH';
export const APPEND_MESSAGE = 'APPEND_MESSAGE';