export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';

export const SUCCESS_NOTIFICATION = 'SUCCESS_NOTIFICATION';
export const ERROR_NOTIFICATION = 'ERROR_NOTIFICATION';

// export const SET_USER = 'SET_USER';
// export const SET_OTHER_USERS = 'SET_OTHER_USERS';
// export const SET_USERNAME_ERR = 'SET_USERNAME_ERR';
// export const SET_PASSWORD_ERR = 'SET_PASSWORD_ERR';
